// Guías de técnica: ejercicios con sus músculos, puntos clave y errores comunes (y su video, cuando exista).
// alias: otros nombres con que la gente lo escribe; con eso Desdel conecta solo tus ejercicios con su guía.
// El id no se cambia nunca (las rutinas lo guardan); video: 'videos/<id>.mp4' cuando esté grabado.
export const GUIDE_ZONES = { pecho: 'Pecho', espalda: 'Espalda', hombros: 'Hombros', brazos: 'Brazos', piernas: 'Piernas', core: 'Core' };

export const GUIDES = [
  // ---------- Pecho ----------
  { id: 'press-banca', zone: 'pecho', name: 'Press banca', alias: ['banca', 'press plano', 'press de banca', 'press banca plano', 'press plano con barra', 'bench press', 'press de pecho con barra'],
    musc: 'Pectoral, tríceps y parte delantera del hombro',
    cues: ['Junta las escápulas y bájalas antes de sacar la barra; mantenlas así toda la serie', 'Pies firmes en el suelo y una leve curva natural en la espalda baja', 'Baja la barra controlada a la parte baja del pecho', 'Codos a unos 45–70° del cuerpo, no abiertos a 90°', 'Sube empujando la barra un poco hacia atrás, sobre los hombros'],
    errs: ['Rebotar la barra en el pecho', 'Levantar el trasero del banco', 'Abrir los codos en línea con los hombros'] },
  { id: 'press-inclinado-barra', zone: 'pecho', name: 'Press inclinado con barra', alias: ['press inclinado', 'banca inclinada', 'inclinado con barra', 'press inclinado barra', 'inclinado smith', 'press inclinado en smith'],
    musc: 'Parte alta del pectoral, hombro delantero y tríceps',
    cues: ['Banco a unos 30–45°', 'Escápulas juntas y bajas, igual que en el press plano', 'Baja la barra a la parte alta del pecho, bajo las clavículas', 'Antebrazos verticales en la parte baja del movimiento'],
    errs: ['Banco demasiado inclinado (se vuelve un press de hombros)', 'Despegar la espalda del banco para empujar'] },
  { id: 'press-inclinado-mancuernas', zone: 'pecho', name: 'Press inclinado con mancuernas', alias: ['inclinado con mancuernas', 'press inclinado mancuernas', 'press inclinado con mancuerna'],
    musc: 'Parte alta del pectoral, hombro delantero y tríceps',
    cues: ['Banco a unos 30–45°', 'Baja las mancuernas a los lados del pecho, sintiendo el estiramiento', 'Codos algo por debajo de los hombros, no abiertos', 'Sube juntando un poco las mancuernas arriba, sin chocarlas'],
    errs: ['Bajar poco (recorrido corto)', 'Dejar caer las mancuernas sin control'] },
  { id: 'press-mancuernas', zone: 'pecho', name: 'Press plano con mancuernas', alias: ['press con mancuernas', 'press banca con mancuernas', 'press plano mancuernas', 'press de pecho con mancuernas'],
    musc: 'Pectoral, tríceps y parte delantera del hombro',
    cues: ['Escápulas juntas y pies firmes', 'Baja hasta sentir el pecho estirado, con las mancuernas a la altura del pecho', 'Codos a unos 45–70° del cuerpo', 'Muñecas firmes, alineadas sobre los codos'],
    errs: ['Abrir demasiado los codos', 'Recorrido corto por usar mucho peso'] },
  { id: 'aperturas', zone: 'pecho', name: 'Aperturas con mancuernas', alias: ['aperturas', 'aperturas planas', 'flyes', 'aperturas en banco', 'aperturas mancuernas'],
    musc: 'Pectoral',
    cues: ['Codos levemente flexionados y fijos durante todo el movimiento', 'Abre los brazos en arco hasta sentir el pecho estirado', 'Sube como si abrazaras un árbol', 'Peso moderado: es un ejercicio de estiramiento, no de fuerza máxima'],
    errs: ['Doblar y estirar los codos (se vuelve un press)', 'Bajar más allá de lo que tus hombros aguantan cómodos'] },
  { id: 'cruces-polea', zone: 'pecho', name: 'Cruces en polea', alias: ['crossover', 'cruce de poleas', 'aperturas en polea', 'cruces', 'cable crossover', 'cruce en polea'],
    musc: 'Pectoral',
    cues: ['Un pie adelante y el torso levemente inclinado', 'Codos levemente flexionados y fijos', 'Lleva las manos juntas frente al pecho, apretando', 'Vuelve lento hasta sentir el estiramiento'],
    errs: ['Tirar con los brazos doblando los codos', 'Balancear el cuerpo para mover el peso'] },
  { id: 'fondos', zone: 'pecho', name: 'Fondos en paralelas', alias: ['fondos', 'dips', 'fondos en paralela', 'paralelas'],
    musc: 'Pectoral (parte baja), tríceps y hombro delantero',
    cues: ['Hombros abajo y lejos de las orejas', 'Baja controlado hasta que los hombros queden a la altura de los codos, o un poco más si es cómodo', 'Torso levemente inclinado adelante para más pecho; más vertical para más tríceps', 'Sube sin bloquear de golpe los codos'],
    errs: ['Encoger los hombros hacia las orejas', 'Bajar más allá de lo cómodo para los hombros'] },
  { id: 'flexiones', zone: 'pecho', name: 'Flexiones de brazos', alias: ['flexiones', 'push ups', 'pushups', 'lagartijas', 'planchas de brazos'],
    musc: 'Pectoral, tríceps, hombro delantero y abdomen',
    cues: ['Manos un poco más anchas que los hombros', 'Cuerpo recto de cabeza a talones: aprieta glúteos y abdomen', 'Codos a unos 45° del cuerpo', 'Baja hasta que el pecho casi toque el suelo'],
    errs: ['Dejar caer la cadera', 'Abrir los codos en T', 'Recorrido corto'] },
  { id: 'press-maquina-pecho', zone: 'pecho', name: 'Press de pecho en máquina', alias: ['press en maquina', 'chest press', 'press pecho maquina', 'maquina de pecho'],
    musc: 'Pectoral, tríceps y hombro delantero',
    cues: ['Ajusta el asiento para que los agarres queden a la altura del pecho medio', 'Escápulas juntas y espalda apoyada', 'Empuja sin bloquear de golpe los codos', 'Vuelve lento hasta sentir el estiramiento'],
    errs: ['Asiento muy alto o muy bajo', 'Despegar la espalda del respaldo'] },
  { id: 'pec-deck', zone: 'pecho', name: 'Pec deck', alias: ['contractor de pecho', 'peck deck', 'maquina de aperturas', 'aperturas en maquina', 'mariposa'],
    musc: 'Pectoral',
    cues: ['Ajusta el asiento para que los brazos queden a la altura del pecho', 'Codos levemente flexionados', 'Junta adelante apretando el pecho, sin chocar los brazos', 'Vuelve lento hasta un estiramiento cómodo'],
    errs: ['Usar impulso', 'Dejar que el peso te tire hacia atrás de golpe'] },

  // ---------- Espalda ----------
  { id: 'dominadas', zone: 'espalda', name: 'Dominadas', alias: ['dominada', 'pull ups', 'pullups', 'dominadas pronas', 'dominadas con lastre'],
    musc: 'Dorsal ancho, bíceps y parte media de la espalda',
    cues: ['Agarre un poco más ancho que los hombros, palmas hacia adelante', 'Empieza bajando los hombros (escápulas) antes de doblar los brazos', 'Sube llevando los codos hacia abajo y hacia las costillas', 'Baja controlado hasta estirar casi por completo los brazos'],
    errs: ['Balancearse o patear para subir', 'Hacer medias repeticiones', 'Subir solo con el mentón estirando el cuello'] },
  { id: 'dominadas-supinas', zone: 'espalda', name: 'Dominadas supinas', alias: ['chin ups', 'chinups', 'dominada supina', 'dominadas agarre supino', 'dominadas cerradas'],
    musc: 'Dorsal ancho y bíceps',
    cues: ['Palmas hacia ti, manos al ancho de los hombros', 'Hombros abajo al empezar', 'Sube hasta que el mentón pase la barra', 'Baja controlado hasta estirar los brazos'],
    errs: ['Balancearse', 'No bajar completo'] },
  { id: 'jalon-pecho', zone: 'espalda', name: 'Jalón al pecho', alias: ['jalon', 'jalon al pecho', 'polea al pecho', 'lat pulldown', 'jalon dorsal', 'polea alta', 'jalon agarre ancho'],
    musc: 'Dorsal ancho, bíceps y parte media de la espalda',
    cues: ['Muslos firmes bajo los rodillos', 'Pecho arriba y torso apenas inclinado atrás', 'Lleva la barra a la parte alta del pecho bajando los codos', 'Sube controlado hasta estirar los brazos y sentir el dorsal'],
    errs: ['Echarse muy atrás y tirar con el cuerpo', 'Bajar la barra detrás de la nuca'] },
  { id: 'remo-barra', zone: 'espalda', name: 'Remo con barra', alias: ['remo', 'remo barra', 'remo inclinado', 'bent over row', 'remo con barra inclinado', 'remo pendlay'],
    musc: 'Espalda media, dorsal, parte trasera del hombro y bíceps',
    cues: ['Rodillas levemente flexionadas y cadera atrás, torso inclinado unos 30–45°', 'Espalda recta y abdomen apretado', 'Lleva la barra hacia el ombligo, juntando las escápulas', 'Baja controlado sin perder la posición'],
    errs: ['Redondear la espalda baja', 'Pararse y tirar con impulso del cuerpo'] },
  { id: 'remo-mancuerna', zone: 'espalda', name: 'Remo con mancuerna', alias: ['remo mancuerna', 'remo a una mano', 'remo unilateral', 'serrucho', 'remo con mancuerna a una mano'],
    musc: 'Dorsal, espalda media y bíceps',
    cues: ['Apoya mano y rodilla en el banco, espalda recta', 'Tira la mancuerna hacia la cadera, no hacia el hombro', 'Codo cerca del cuerpo', 'Baja hasta estirar el brazo y sentir el dorsal'],
    errs: ['Girar el torso para subir más peso', 'Tirar con el bíceps en vez de la espalda'] },
  { id: 'remo-polea', zone: 'espalda', name: 'Remo en polea baja', alias: ['remo sentado', 'remo en polea', 'seated row', 'remo gironda', 'remo polea baja', 'remo con triangulo'],
    musc: 'Espalda media, dorsal y bíceps',
    cues: ['Rodillas levemente flexionadas y pecho arriba', 'Tira hacia el abdomen juntando las escápulas', 'Codos cerca del cuerpo', 'Al volver, deja que los brazos se estiren y la escápula se adelante un poco'],
    errs: ['Mecerse adelante y atrás con todo el torso', 'Encoger los hombros'] },
  { id: 'remo-maquina', zone: 'espalda', name: 'Remo en máquina', alias: ['remo maquina', 'remo en t', 'remo t', 'remo con apoyo de pecho', 'remo hammer', 't bar row'],
    musc: 'Espalda media, dorsal y bíceps',
    cues: ['Pecho apoyado firme en el respaldo', 'Tira llevando los codos atrás y juntando las escápulas', 'Pausa breve atrás', 'Estira completo al volver'],
    errs: ['Despegar el pecho del apoyo', 'Recorrido corto'] },
  { id: 'pullover-polea', zone: 'espalda', name: 'Pullover en polea', alias: ['pullover', 'pull over', 'pullover con cuerda', 'pulldown brazos rectos', 'straight arm pulldown'],
    musc: 'Dorsal ancho',
    cues: ['Torso levemente inclinado adelante, brazos casi rectos', 'Baja la barra o cuerda en arco hasta los muslos', 'Siente cómo el dorsal tira, no los tríceps', 'Sube controlado hasta estirar arriba'],
    errs: ['Doblar los codos (se vuelve un jalón de tríceps)', 'Mover el torso para ayudar'] },
  { id: 'peso-muerto', zone: 'espalda', name: 'Peso muerto', alias: ['peso muerto convencional', 'deadlift', 'muerto'],
    musc: 'Glúteos, isquiotibiales, espalda baja, espalda alta y antebrazos',
    cues: ['Barra sobre la mitad del pie, pegada a las canillas', 'Toma aire, aprieta el abdomen y "saca" el pecho antes de tirar', 'Empuja el suelo con los pies; la barra sube pegada al cuerpo', 'Termina de pie con glúteos apretados, sin echarte atrás', 'Baja con la cadera atrás, la barra rozando las piernas'],
    errs: ['Redondear la espalda baja', 'Barra lejos del cuerpo', 'Levantar primero la cadera y después la espalda'] },
  { id: 'face-pull', zone: 'hombros', name: 'Face pull', alias: ['facepull', 'face pulls', 'jalon a la cara', 'tiron a la cara'],
    musc: 'Parte trasera del hombro, manguito rotador y espalda alta',
    cues: ['Polea a la altura de la cara, con cuerda', 'Tira hacia la cara separando las manos', 'Codos altos, terminando con las manos al lado de las orejas', 'Pausa breve y vuelve controlado'],
    errs: ['Usar mucho peso y echarse atrás', 'Bajar los codos (se vuelve un remo)'] },
  { id: 'hiperextensiones', zone: 'espalda', name: 'Hiperextensiones', alias: ['lumbares', 'extensiones lumbares', 'hiperextension', 'banco romano', 'back extension'],
    musc: 'Espalda baja, glúteos e isquiotibiales',
    cues: ['El apoyo a la altura de la cadera, no del abdomen', 'Baja con la espalda recta doblándote desde la cadera', 'Sube hasta quedar en línea recta con las piernas', 'Aprieta glúteos arriba'],
    errs: ['Subir de más arqueando mucho la espalda', 'Hacerlo rápido con rebote'] },

  // ---------- Hombros ----------
  { id: 'press-militar', zone: 'hombros', name: 'Press militar', alias: ['press militar de pie', 'press de hombros con barra', 'overhead press', 'ohp', 'press militar barra'],
    musc: 'Hombro (deltoide frontal y lateral) y tríceps',
    cues: ['Barra sobre la parte alta del pecho, agarre un poco más ancho que los hombros', 'Glúteos y abdomen apretados para no arquear la espalda', 'Empuja la barra en línea recta y mete la cabeza "por la ventana" al pasar', 'Termina con la barra sobre la mitad del pie'],
    errs: ['Arquear mucho la espalda baja', 'Empujar la barra hacia adelante, lejos del cuerpo'] },
  { id: 'press-hombros-mancuernas', zone: 'hombros', name: 'Press de hombros con mancuernas', alias: ['press hombros mancuernas', 'press militar con mancuernas', 'press arnold', 'press de hombro sentado', 'press de hombros'],
    musc: 'Hombro (deltoide frontal y lateral) y tríceps',
    cues: ['Respaldo casi vertical y espalda apoyada', 'Mancuernas a la altura de las orejas, codos un poco adelante del cuerpo', 'Empuja hacia arriba sin chocarlas', 'Baja controlado hasta la altura de las orejas o un poco más'],
    errs: ['Despegar la espalda y arquearse', 'Bajar muy poco'] },
  { id: 'elevaciones-laterales', zone: 'hombros', name: 'Elevaciones laterales', alias: ['laterales', 'vuelos laterales', 'elevacion lateral', 'lateral raise', 'laterales con mancuernas', 'laterales mancuerna', 'laterales manc'],
    musc: 'Hombro (deltoide lateral)',
    cues: ['Codos levemente flexionados', 'Sube los brazos hacia los lados, llevando los codos hacia afuera', 'Sube hasta la altura de los hombros', 'Baja lento, sin dejar caer las mancuernas'],
    errs: ['Balancear el cuerpo para subir', 'Encoger los hombros (trabaja el trapecio)', 'Subir con los codos más bajos que las manos'] },
  { id: 'laterales-polea', zone: 'hombros', name: 'Elevaciones laterales en polea', alias: ['laterales en polea', 'lateral en polea', 'elevacion lateral polea', 'laterales cable'],
    musc: 'Hombro (deltoide lateral)',
    cues: ['Polea baja, del lado contrario al brazo que trabaja', 'Sube el brazo hacia el lado hasta la altura del hombro', 'Codo levemente flexionado', 'La polea mantiene tensión abajo: aprovecha esa parte'],
    errs: ['Inclinar el cuerpo para mover el peso', 'Encoger el hombro'] },
  { id: 'pajaros', zone: 'hombros', name: 'Pájaros', alias: ['pajaro', 'vuelos posteriores', 'aperturas invertidas', 'reverse fly', 'posterior con mancuernas', 'deltoide posterior', 'peck deck invertido', 'reverse pec deck'],
    musc: 'Parte trasera del hombro y espalda alta',
    cues: ['Torso inclinado adelante o pecho apoyado en un banco inclinado', 'Codos levemente flexionados', 'Abre los brazos hacia los lados pensando en llevar los codos lejos', 'Peso liviano y movimiento controlado'],
    errs: ['Juntar las escápulas y tirar con la espalda en vez del hombro', 'Usar impulso'] },
  { id: 'encogimientos', zone: 'hombros', name: 'Encogimientos', alias: ['encogimientos de hombros', 'trapecio', 'shrugs', 'encogimiento'],
    musc: 'Trapecio superior',
    cues: ['De pie, peso a los lados o al frente', 'Sube los hombros hacia las orejas, en línea recta', 'Pausa breve arriba', 'Baja completo y controlado'],
    errs: ['Hacer círculos con los hombros', 'Recorrido corto con mucho peso'] },

  // ---------- Brazos ----------
  { id: 'curl-barra', zone: 'brazos', name: 'Curl con barra', alias: ['curl barra', 'curl de biceps con barra', 'biceps con barra', 'curl barra z', 'curl con barra z'],
    musc: 'Bíceps y braquial',
    cues: ['Codos pegados a los costados', 'Sube sin mover los codos hacia adelante', 'Aprieta arriba y baja lento hasta estirar los brazos', 'Torso quieto'],
    errs: ['Balancear el cuerpo', 'No estirar completo abajo'] },
  { id: 'curl-mancuernas', zone: 'brazos', name: 'Curl con mancuernas', alias: ['curl mancuernas', 'curl de biceps', 'biceps', 'curl alterno', 'curl biceps mancuernas', 'curl de biceps con mancuernas'],
    musc: 'Bíceps y braquial',
    cues: ['Codos quietos a los costados', 'Gira la palma hacia arriba mientras subes', 'Aprieta arriba', 'Baja controlado hasta estirar el brazo'],
    errs: ['Usar impulso de la cadera', 'Subir el codo al final'] },
  { id: 'curl-martillo', zone: 'brazos', name: 'Curl martillo', alias: ['martillo', 'curl martillo mancuernas', 'hammer curl', 'curl neutro'],
    musc: 'Braquial, braquiorradial (antebrazo) y bíceps',
    cues: ['Palmas mirándose entre sí todo el movimiento', 'Codos quietos a los costados', 'Sube y baja controlado'],
    errs: ['Balancear el cuerpo', 'Mover los codos hacia adelante'] },
  { id: 'curl-inclinado', zone: 'brazos', name: 'Curl inclinado', alias: ['curl en banco inclinado', 'curl inclinado mancuernas', 'incline curl'],
    musc: 'Bíceps (sobre todo en la parte estirada)',
    cues: ['Banco a unos 45–60°, brazos colgando detrás del torso', 'Sube sin adelantar los codos', 'Baja lento hasta estirar completo: ahí está lo bueno del ejercicio'],
    errs: ['Adelantar los hombros y los codos', 'Usar demasiado peso y acortar el recorrido'] },
  { id: 'curl-predicador', zone: 'brazos', name: 'Curl predicador', alias: ['curl scott', 'banco scott', 'predicador', 'curl en banco scott', 'curl concentrado'],
    musc: 'Bíceps y braquial',
    cues: ['Axilas apoyadas arriba del cojín', 'Baja controlado hasta casi estirar el brazo', 'Sube sin despegar los brazos del cojín'],
    errs: ['Dejar caer el peso abajo (estresa el codo)', 'Levantar los codos del apoyo'] },
  { id: 'triceps-polea', zone: 'brazos', name: 'Extensión de tríceps en polea', alias: ['triceps en polea', 'jalon de triceps', 'pushdown', 'triceps con cuerda', 'triceps polea', 'extension de triceps en polea', 'triceps con barra en polea'],
    musc: 'Tríceps',
    cues: ['Codos pegados a los costados y fijos', 'Estira los brazos completo abajo y aprieta', 'Sube controlado hasta que los antebrazos queden casi horizontales', 'Torso quieto, levemente inclinado'],
    errs: ['Mover los codos hacia adelante y atrás', 'Echarse encima del peso para empujar con el cuerpo'] },
  { id: 'triceps-sobre-cabeza', zone: 'brazos', name: 'Extensión de tríceps sobre la cabeza', alias: ['triceps tras nuca', 'extension tras nuca', 'triceps sobre la cabeza', 'overhead triceps', 'extension de triceps con mancuerna', 'triceps frances con mancuerna'],
    musc: 'Tríceps (sobre todo la cabeza larga)',
    cues: ['Codos apuntando hacia arriba, cerca de la cabeza', 'Baja el peso detrás de la cabeza hasta sentir el tríceps estirado', 'Estira los brazos sin abrir los codos', 'Abdomen apretado para no arquear la espalda'],
    errs: ['Abrir mucho los codos', 'Arquear la espalda baja'] },
  { id: 'press-frances', zone: 'brazos', name: 'Press francés', alias: ['frances', 'skull crusher', 'rompecraneos', 'press frances con barra', 'extension de triceps acostado'],
    musc: 'Tríceps',
    cues: ['Acostado, brazos verticales o levemente inclinados hacia la cabeza', 'Baja la barra doblando solo los codos, hacia la frente o detrás de la cabeza', 'Codos apuntando al techo, sin abrirse', 'Sube estirando los brazos'],
    errs: ['Mover los hombros (se vuelve un press)', 'Abrir los codos hacia los lados'] },
  { id: 'press-cerrado', zone: 'brazos', name: 'Press banca cerrado', alias: ['press cerrado', 'banca agarre cerrado', 'close grip bench', 'press agarre cerrado'],
    musc: 'Tríceps, pectoral y hombro delantero',
    cues: ['Agarre al ancho de los hombros (no más cerrado)', 'Codos pegados al cuerpo al bajar', 'Barra a la parte baja del pecho', 'Escápulas juntas como en el press banca'],
    errs: ['Agarre demasiado cerrado (molesta las muñecas)', 'Abrir los codos'] },

  // ---------- Piernas ----------
  { id: 'sentadilla', zone: 'piernas', name: 'Sentadilla', alias: ['sentadilla con barra', 'squat', 'sentadilla libre', 'sentadilla trasera', 'back squat', 'sentadillas'],
    musc: 'Cuádriceps, glúteos y aductores',
    cues: ['Barra sobre la parte alta de la espalda, no sobre el cuello', 'Pies al ancho de hombros o un poco más, puntas algo hacia afuera', 'Toma aire y aprieta el abdomen antes de bajar', 'Baja con las rodillas en la dirección de los pies, sin que se vayan hacia adentro', 'Baja lo más profundo que puedas manteniendo la espalda neutra y los talones apoyados'],
    errs: ['Rodillas hacia adentro al subir', 'Levantar los talones', 'Redondear la espalda abajo'] },
  { id: 'sentadilla-frontal', zone: 'piernas', name: 'Sentadilla frontal', alias: ['front squat', 'sentadilla frontal con barra', 'sentadilla delantera'],
    musc: 'Cuádriceps, glúteos y espalda alta',
    cues: ['Barra apoyada sobre los hombros delanteros, codos altos', 'Torso más vertical que en la sentadilla normal', 'Baja profundo con las rodillas hacia adelante y afuera', 'Mantén los codos arriba al subir'],
    errs: ['Bajar los codos (la barra se va hacia adelante)', 'Redondear la espalda alta'] },
  { id: 'sentadilla-bulgara', zone: 'piernas', name: 'Sentadilla búlgara', alias: ['bulgara', 'bulgaras', 'split squat', 'sentadilla bulgara con mancuernas', 'zancada bulgara'],
    musc: 'Cuádriceps y glúteos',
    cues: ['Pie trasero apoyado en un banco, pie delantero bien adelante', 'Baja recto hacia abajo hasta que la rodilla trasera casi toque el suelo', 'Rodilla delantera en línea con el pie', 'Torso más inclinado = más glúteo; más vertical = más cuádriceps'],
    errs: ['Pie delantero muy cerca del banco', 'Rodilla delantera hacia adentro'] },
  { id: 'prensa', zone: 'piernas', name: 'Prensa de piernas', alias: ['prensa', 'leg press', 'prensa 45', 'prensa inclinada', 'prensa de pierna'],
    musc: 'Cuádriceps y glúteos',
    cues: ['Espalda y cadera bien apoyadas en el respaldo', 'Pies al ancho de los hombros en la mitad de la plataforma', 'Baja hasta donde tu cadera no se despegue del asiento', 'Empuja con todo el pie sin bloquear de golpe las rodillas'],
    errs: ['Despegar la cadera abajo (redondea la espalda baja)', 'Bloquear las rodillas de golpe arriba', 'Recorrido muy corto con mucho peso'] },
  { id: 'hack', zone: 'piernas', name: 'Sentadilla hack', alias: ['hack', 'hack squat', 'sentadilla en maquina', 'maquina hack', 'pendulo', 'sentadilla pendulo'],
    musc: 'Cuádriceps y glúteos',
    cues: ['Espalda apoyada y hombros bajo los cojines', 'Pies en la mitad de la plataforma, al ancho de hombros', 'Baja profundo con las rodillas hacia adelante', 'Sube empujando con todo el pie'],
    errs: ['Recorrido corto', 'Rodillas hacia adentro'] },
  { id: 'zancadas', zone: 'piernas', name: 'Zancadas', alias: ['estocadas', 'lunges', 'desplantes', 'zancadas con mancuernas', 'zancada', 'estocada', 'zancadas caminando'],
    musc: 'Cuádriceps y glúteos',
    cues: ['Da un paso largo y baja hasta que la rodilla de atrás casi toque el suelo', 'Rodilla delantera en línea con el pie', 'Torso firme', 'Empuja con el talón delantero para volver'],
    errs: ['Paso muy corto (carga mucho la rodilla)', 'Rodilla delantera hacia adentro'] },
  { id: 'peso-muerto-rumano', zone: 'piernas', name: 'Peso muerto rumano', alias: ['rumano', 'peso muerto piernas rigidas', 'rdl', 'peso muerto rumano con mancuernas', 'peso muerto rumano con barra', 'muerto rumano'],
    musc: 'Isquiotibiales y glúteos',
    cues: ['Rodillas levemente flexionadas y fijas', 'Baja llevando la cadera hacia atrás, con la barra pegada a las piernas', 'Espalda neutra todo el recorrido', 'Baja hasta sentir el estiramiento atrás de los muslos (suele ser bajo la rodilla)', 'Sube empujando la cadera adelante'],
    errs: ['Redondear la espalda para bajar más', 'Doblar mucho las rodillas (se vuelve sentadilla)', 'Barra lejos de las piernas'] },
  { id: 'curl-femoral-acostado', zone: 'piernas', name: 'Curl femoral acostado', alias: ['curl femoral', 'femoral acostado', 'femorales', 'leg curl', 'curl de isquiotibiales', 'femoral'],
    musc: 'Isquiotibiales',
    cues: ['Rodilla alineada con el eje de la máquina', 'Cadera pegada al banco', 'Sube los talones hacia los glúteos y aprieta', 'Baja lento hasta estirar casi completo'],
    errs: ['Levantar la cadera para ayudarte', 'Dejar caer el peso al bajar'] },
  { id: 'curl-femoral-sentado', zone: 'piernas', name: 'Curl femoral sentado', alias: ['femoral sentado', 'seated leg curl', 'curl femoral en maquina sentado'],
    musc: 'Isquiotibiales',
    cues: ['Rodilla alineada con el eje de la máquina y muslo bien sujeto', 'Torso levemente inclinado adelante para estirar más', 'Baja el rodillo hasta atrás y aprieta', 'Vuelve controlado hasta estirar'],
    errs: ['Recorrido corto', 'Despegar el muslo del asiento'] },
  { id: 'extension-cuadriceps', zone: 'piernas', name: 'Extensión de cuádriceps', alias: ['extension de piernas', 'extensiones', 'leg extension', 'sillon de cuadriceps', 'extension cuadriceps', 'cuadriceps en maquina'],
    musc: 'Cuádriceps',
    cues: ['Rodilla alineada con el eje de la máquina', 'Espalda apoyada y agarra los mangos', 'Estira las piernas completo y aprieta arriba', 'Baja lento hasta doblar bien la rodilla'],
    errs: ['Patear el peso con impulso', 'Recorrido corto abajo'] },
  { id: 'hip-thrust', zone: 'piernas', name: 'Hip thrust', alias: ['empuje de cadera', 'hip thrust con barra', 'puente de gluteo con barra', 'hipthrust', 'elevacion de cadera'],
    musc: 'Glúteos',
    cues: ['Parte alta de la espalda apoyada en el banco, barra sobre la cadera (con protector)', 'Pies al ancho de las caderas; arriba, las canillas quedan verticales', 'Sube empujando con los talones y aprieta los glúteos', 'Mentón levemente hacia el pecho y costillas abajo'],
    errs: ['Arquear la espalda baja arriba en vez de extender la cadera', 'Pies muy lejos (trabaja más el isquiotibial)'] },
  { id: 'patada-gluteo', zone: 'piernas', name: 'Patada de glúteo en polea', alias: ['patada de gluteo', 'patada en polea', 'kickback', 'gluteo en polea', 'patada trasera'],
    musc: 'Glúteos',
    cues: ['Torso levemente inclinado y firme', 'Lleva la pierna hacia atrás apretando el glúteo', 'Sin arquear la espalda baja', 'Vuelve controlado'],
    errs: ['Arquear la espalda para subir más', 'Balancear la pierna'] },
  { id: 'abductores', zone: 'piernas', name: 'Abductores en máquina', alias: ['abductores', 'abductor', 'maquina de abductores', 'aperturas de cadera', 'hip abduction'],
    musc: 'Glúteo medio y menor',
    cues: ['Espalda apoyada (o torso levemente inclinado adelante para más glúteo)', 'Abre las piernas controlado', 'Pausa breve afuera', 'Vuelve lento sin que las placas choquen'],
    errs: ['Hacerlo rápido con rebote', 'Usar el impulso del cuerpo'] },
  { id: 'aductores', zone: 'piernas', name: 'Aductores en máquina', alias: ['aductores', 'aductor', 'maquina de aductores', 'hip adduction'],
    musc: 'Aductores (parte interna del muslo)',
    cues: ['Espalda apoyada', 'Empieza con un estiramiento cómodo, sin forzar', 'Junta las piernas apretando', 'Vuelve lento'],
    errs: ['Abrir más de lo cómodo al inicio', 'Rebotar'] },
  { id: 'pantorrillas-pie', zone: 'piernas', name: 'Elevación de talones de pie', alias: ['pantorrillas', 'gemelos', 'elevacion de talones', 'calf raise', 'pantorrilla de pie', 'gemelos de pie', 'pantorrillas en maquina'],
    musc: 'Gemelos (pantorrilla)',
    cues: ['Punta de los pies sobre un escalón o plataforma', 'Baja lo más que puedas y haz una pausa abajo, estirado', 'Sube lo más alto posible', 'Rodillas estiradas pero sin trabarlas'],
    errs: ['Rebotar abajo', 'Recorrido corto y rápido'] },
  { id: 'pantorrillas-sentado', zone: 'piernas', name: 'Elevación de talones sentado', alias: ['pantorrilla sentado', 'gemelos sentado', 'soleo', 'seated calf raise'],
    musc: 'Sóleo (pantorrilla)',
    cues: ['Rodillas dobladas bajo el cojín', 'Baja hasta estirar bien con una pausa', 'Sube lo más alto posible'],
    errs: ['Rebotar', 'Hacer medias repeticiones'] },
  { id: 'peso-muerto-sumo', zone: 'piernas', name: 'Peso muerto sumo', alias: ['sumo', 'peso muerto sumo con barra', 'sumo deadlift'],
    musc: 'Glúteos, aductores, cuádriceps y espalda',
    cues: ['Pies bien abiertos y puntas hacia afuera', 'Manos por dentro de las piernas, brazos verticales', 'Rodillas empujando hacia afuera, en la dirección de los pies', 'Pecho arriba, espalda neutra; empuja el suelo hacia los lados'],
    errs: ['Rodillas hacia adentro', 'Cadera muy alta al empezar'] },

  // ---------- Core ----------
  { id: 'plancha', zone: 'core', name: 'Plancha', alias: ['plancha abdominal', 'plank', 'plancha frontal'],
    musc: 'Abdomen y músculos que estabilizan el tronco',
    cues: ['Antebrazos bajo los hombros', 'Cuerpo recto de cabeza a talones', 'Aprieta glúteos y abdomen, como si te fueran a golpear', 'Respira normal'],
    errs: ['Dejar caer la cadera', 'Subir mucho la cadera'] },
  { id: 'crunch-polea', zone: 'core', name: 'Crunch en polea', alias: ['abdominal en polea', 'crunch con cuerda', 'abdominales en polea', 'cable crunch', 'crunch arrodillado'],
    musc: 'Recto abdominal',
    cues: ['Arrodillado, cuerda a los lados de la cabeza', 'Enrolla la columna llevando las costillas hacia la pelvis', 'La cadera se queda quieta', 'Vuelve lento estirando el abdomen'],
    errs: ['Tirar con los brazos', 'Sentarse sobre los talones moviendo la cadera'] },
  { id: 'elevacion-piernas', zone: 'core', name: 'Elevación de piernas colgado', alias: ['elevacion de piernas', 'leg raises', 'abdominales colgado', 'elevacion de rodillas', 'hanging leg raise'],
    musc: 'Abdomen (sobre todo la parte baja) y flexores de la cadera',
    cues: ['Cuelga con los hombros activos, sin balancearte', 'Sube las piernas enrollando la pelvis hacia arriba', 'Si cuesta, sube las rodillas dobladas', 'Baja controlado'],
    errs: ['Balancearse para subir', 'Subir solo las piernas sin enrollar la pelvis'] },
  { id: 'rueda-abdominal', zone: 'core', name: 'Rueda abdominal', alias: ['rueda', 'ab wheel', 'rodillo abdominal', 'rollout'],
    musc: 'Abdomen y músculos que estabilizan el tronco',
    cues: ['Parte de rodillas, abdomen apretado y glúteos firmes', 'Avanza hasta donde puedas sin que se hunda la espalda baja', 'Vuelve tirando con el abdomen', 'Avanza más a medida que te haces más fuerte'],
    errs: ['Arquear la espalda baja', 'Ir más lejos de lo que puedes controlar'] },
];
