// Preguntas del Quiz entre series: [id, categoría, pregunta, alternativas, índice de la correcta, explicación, nivel]
// nivel: se omite en las básicas; 2 = difícil (se muestra "Difícil" en la tarjeta).
// Categorías: e = Entrenamiento, n = Nutrición, s = Salud y recuperación.
// El id no se cambia nunca (con él se recuerda qué preguntas ya viste); para sacar una pregunta, bórrala entera.
export const QUIZ_CATS = { e: 'Entrenamiento', n: 'Nutrición', s: 'Salud y recuperación' };

export const QUIZ = [
  // ---------- Entrenamiento ----------
  ['e1', 'e', '¿Qué significa terminar una serie con RIR 2?', ['Que hiciste 2 series', 'Que te quedaban 2 reps antes del fallo', 'Que descansaste 2 minutos'], 1,
    'RIR = repeticiones en reserva: cuántas reps más podrías haber hecho con buena técnica.'],
  ['e2', 'e', '¿Qué es la sobrecarga progresiva?', ['Entrenar hasta no poder más cada día', 'Subir de a poco el peso, las reps o las series', 'Cambiar de rutina cada semana'], 1,
    'Para seguir progresando, el estímulo tiene que aumentar con el tiempo. Es la base de todo programa.'],
  ['e3', 'e', '¿Cuánto conviene descansar entre series pesadas de sentadilla?', ['30 segundos', '2 a 3 minutos o más', '10 minutos'], 1,
    'En ejercicios grandes y pesados, descansos de 2 a 3 minutos o más permiten rendir mejor en la serie siguiente.'],
  ['e4', 'e', 'Para ganar músculo, ¿cuántas series duras por músculo a la semana son un buen punto de partida?', ['2 a 4', '10 a 20', '40 o más'], 1,
    'Entre 10 y 20 series semanales por músculo es un rango que funciona para la mayoría. Más no siempre es mejor.'],
  ['e5', 'e', '¿Qué es tu 1RM?', ['El peso de tu primera serie', 'El máximo peso que puedes levantar 1 vez', 'Las reps que haces en 1 minuto'], 1,
    '1RM = 1 repetición máxima. Desdel lo estima con tus series para mostrar tu progreso.'],
  ['e6', 'e', '¿En qué rango de reps se puede ganar músculo?', ['Solo entre 8 y 12', 'En un rango amplio (aprox. 6 a 30) si llegas cerca del fallo', 'Solo con 1 a 3 reps'], 1,
    'Lo clave es acercarse al fallo. Con pesos más livianos y más reps también se gana músculo.'],
  ['e7', 'e', 'Para mejorar tu fuerza máxima, ¿qué funciona mejor?', ['Reps bajas (1 a 5) con pesos altos', 'Series de 25 reps livianas', 'Solo máquinas de cable'], 0,
    'La fuerza máxima se entrena levantando pesos cercanos a tu máximo, con pocas reps y buena técnica.'],
  ['e8', 'e', '¿Cuál es una buena forma de calentar antes de un ejercicio pesado?', ['Hacer series de aproximación con menos peso', 'Estirar 20 minutos sin moverse', 'Empezar directo con el peso máximo'], 0,
    'Subir el peso de a poco (por ejemplo 50 %, 70 %, 85 %) prepara músculos, articulaciones y técnica.'],
  ['e9', 'e', '¿Cuántas veces por semana conviene entrenar cada músculo como punto de partida?', ['1 vez cada 2 semanas', '2 veces', 'Todos los días'], 1,
    'Dos veces por semana es un buen punto de partida. Lo que más importa es el total de series semanales.'],
  ['e10', 'e', '¿Qué es un dropset?', ['Bajar el peso al terminar la serie y seguir sin descansar', 'Soltar la barra al final', 'Hacer una serie con un solo brazo'], 0,
    'Llegas cerca del fallo, bajas el peso y sigues. Es una forma de sumar trabajo en poco tiempo.'],
  ['e11', 'e', '¿Qué es una superserie?', ['Una serie de 50 reps', 'Dos ejercicios seguidos, alternándolos sin descanso entre ellos', 'Una serie con el doble de peso'], 1,
    'Ejemplo: bíceps y tríceps intercalados. Ahorra tiempo sin perder mucho rendimiento.'],
  ['e12', 'e', '¿Qué es llegar al fallo muscular?', ['Que te duela al día siguiente', 'No poder hacer otra rep con buena técnica', 'Terminar la rutina completa'], 1,
    'Es el punto en que ya no sale otra repetición completa y bien hecha (RIR 0).'],
  ['e13', 'e', 'En general, ¿qué recorrido conviene usar en los ejercicios?', ['El recorrido completo, sobre todo la parte estirada', 'Siempre medias repeticiones', 'Da lo mismo siempre'], 0,
    'El recorrido completo, especialmente la parte donde el músculo se estira, suele dar mejores resultados.'],
  ['e14', 'e', '¿Qué es una semana de descarga (deload)?', ['Una semana más suave para recuperarte', 'Una semana sin comer carbohidratos', 'Una semana entrenando el doble'], 0,
    'Bajar el volumen o el peso por unos días ayuda a eliminar fatiga acumulada y volver más fuerte.'],
  ['e15', 'e', '¿Qué músculos trabaja principalmente la sentadilla?', ['Cuádriceps y glúteos', 'Bíceps y antebrazos', 'Pecho y hombros'], 0,
    'También trabajan aductores y la zona media, pero los protagonistas son cuádriceps y glúteos.'],
  ['e16', 'e', '¿Qué trabajan principalmente las dominadas?', ['Pecho y tríceps', 'Dorsal (espalda) y bíceps', 'Cuádriceps'], 1,
    'Es uno de los mejores ejercicios para la espalda, con mucha ayuda de los bíceps.'],
  ['e17', 'e', '¿Qué músculos trabaja el press banca?', ['Pectoral, tríceps y parte delantera del hombro', 'Espalda y bíceps', 'Glúteos'], 0,
    'Es un empuje horizontal: el pecho hace la mayor parte, con ayuda de tríceps y hombros.'],
  ['e18', 'e', '¿Qué trabaja sobre todo el peso muerto rumano?', ['Cuádriceps', 'Isquiotibiales y glúteos', 'Abdominales'], 1,
    'Al bajar con la cadera hacia atrás, los isquiotibiales se estiran bajo carga.'],
  ['e19', 'e', '¿Qué músculo trabaja principalmente el hip thrust?', ['Glúteos', 'Pantorrillas', 'Pecho'], 0,
    'Es uno de los ejercicios con más activación de glúteos.'],
  ['e20', 'e', '¿Qué trabajan las elevaciones laterales?', ['La parte lateral del hombro (deltoide lateral)', 'El bíceps', 'La espalda baja'], 0,
    'El deltoide lateral es el que da el ancho de hombros.'],
  ['e21', 'e', '¿Qué trabaja principalmente el face pull?', ['La parte trasera del hombro y la parte alta de la espalda', 'El pecho', 'Los cuádriceps'], 0,
    'Ayuda a equilibrar todo el trabajo de empuje y a cuidar los hombros.'],
  ['e22', 'e', '¿Cuándo crece el músculo?', ['Solo mientras entrenas', 'Mientras te recuperas, con descanso y comida', 'Solo si entrenas todos los días'], 1,
    'El entreno da el estímulo; el músculo se reconstruye y crece en la recuperación.'],
  ['e23', 'e', 'Si al día siguiente no te duele nada, ¿el entreno no sirvió?', ['Sí, sin dolor no hay resultados', 'No: el dolor no mide qué tan efectivo fue', 'Solo sirvió la mitad'], 1,
    'El dolor muscular baja a medida que te acostumbras. Mira tu progreso en peso y reps, no el dolor.'],
  ['e24', 'e', '¿Qué es la fase excéntrica de un ejercicio?', ['Cuando el músculo se alarga bajo carga (ej. bajar la barra)', 'Cuando el músculo se acorta', 'La pausa entre series'], 0,
    'Controlar la bajada en vez de dejar caer el peso aprovecha mejor cada repetición.'],
  ['e25', 'e', 'Antes de una rep pesada de sentadilla, ¿qué conviene hacer con la respiración?', ['Soltar todo el aire', 'Tomar aire y apretar el abdomen', 'Hablar para relajarte'], 1,
    'Tomar aire y apretar el abdomen (bracing) estabiliza el tronco y protege la espalda.'],
  ['e26', 'e', '¿Hacer cardio te impide ganar músculo?', ['Sí, siempre', 'No, si es moderado y comes y descansas bien', 'Solo si es caminar'], 1,
    'El cardio moderado casi no interfiere y suma mucho a tu salud y tu corazón.'],
  ['e27', 'e', '¿Máquinas o pesos libres para ganar músculo?', ['Solo pesos libres', 'Solo máquinas', 'Ambos sirven si progresas en ellos'], 2,
    'El músculo no sabe qué herramienta usas: responde a la tensión y a la progresión.'],
  ['e28', 'e', 'Al empezar a entrenar, ¿cuándo se suelen notar cambios visibles?', ['A la semana', 'Después de unas 6 a 12 semanas constantes', 'Después de 3 años'], 1,
    'La fuerza sube rápido al principio; los cambios visibles toman unas semanas de constancia.'],
  ['e29', 'e', '¿Quién suele progresar más rápido?', ['Quien recién empieza', 'Quien lleva 10 años', 'Todos igual'], 0,
    'Son las "ganancias de novato": al principio el cuerpo responde muy rápido al entrenamiento.'],
  ['e30', 'e', 'Si la técnica se rompe al subir de peso, ¿qué conviene hacer?', ['Seguir igual', 'Bajar el peso y hacerlo bien', 'Hacer las reps más rápido'], 1,
    'Con buena técnica trabajas el músculo correcto y reduces el riesgo de lesión.'],
  ['e31', 'e', '¿El cinturón de levantamiento es obligatorio?', ['Sí, siempre', 'No: ayuda en levantamientos muy pesados, pero es opcional', 'Solo sirve para bajar la guata'], 1,
    'Ayuda a hacer presión abdominal en series pesadas. Primero conviene aprender a apretar sin él.'],
  ['e32', 'e', 'Justo antes de levantar pesado, ¿qué tipo de estiramiento conviene?', ['Estiramientos estáticos largos (más de 1 minuto)', 'Movilidad y calentamiento dinámico', 'Ninguno, nunca'], 1,
    'Los estiramientos estáticos largos justo antes pueden bajar un poco la fuerza. Deja los largos para después.'],
  ['e33', 'e', '¿La sentadilla profunda daña las rodillas?', ['Sí, siempre', 'No, con buena técnica y carga adecuada en rodillas sanas', 'Solo los lunes'], 1,
    'Bajar profundo con control es seguro para rodillas sanas y trabaja más músculo.'],
  ['e34', 'e', 'En la sentadilla, ¿está mal que las rodillas pasen la punta de los pies?', ['Sí, siempre', 'No: es normal en muchas personas', 'Solo con barra'], 1,
    'Depende de tu cuerpo y tu técnica. Lo importante es que los talones se queden apoyados.'],
  ['e35', 'e', '¿Qué es el volumen de entrenamiento?', ['El volumen de la música del gym', 'La cantidad total de trabajo: series, reps y peso', 'El tamaño de tus músculos'], 1,
    'Una forma simple de medirlo es contar las series duras por músculo a la semana.'],
  ['e36', 'e', '¿Qué es la periodización?', ['Planificar cómo cambian el volumen y la intensidad en el tiempo', 'Entrenar solo en ciertos meses', 'Cambiar de gym'], 0,
    'Organizar el entrenamiento por etapas ayuda a progresar y a evitar estancarse.'],
  ['e37', 'e', '¿Para qué sirven las correas (straps)?', ['Para cuando tu agarre falla antes que tu espalda', 'Para hacer más bonita la foto', 'Para no transpirar'], 0,
    'En remos o pesos muertos, te permiten trabajar la espalda aunque se canse el antebrazo.'],
  ['e38', 'e', '¿Para qué sirven los ejercicios a una pierna o un brazo (ej. zancadas)?', ['Para corregir diferencias entre un lado y el otro', 'Para nada', 'Solo para calentar'], 0,
    'También trabajan el equilibrio y la estabilidad.'],
  ['e39', 'e', '¿Qué trabaja la plancha?', ['El abdomen y los músculos que estabilizan el tronco', 'Solo los brazos', 'Las pantorrillas'], 0,
    'Es un ejercicio isométrico: el tronco se mantiene firme sin moverse.'],
  ['e40', 'e', '¿Qué es el "pump" (bombeo)?', ['Crecimiento muscular permanente', 'Acumulación temporal de sangre en el músculo', 'Una lesión'], 1,
    'Se siente bien, pero se va en unas horas. El crecimiento real se mide en semanas.'],
  ['e41', 'e', '¿Qué tan cerca del fallo conviene terminar la mayoría de las series para ganar músculo?', ['A 0–3 reps del fallo', 'A 10 reps del fallo', 'Da lo mismo'], 0,
    'Las series que terminan cerca del fallo (RIR 0 a 3) son las que más estímulo dan.'],
  ['e42', 'e', '¿Conviene llevar al fallo todas las series?', ['Sí, siempre', 'No: aumenta mucho la fatiga y no es necesario', 'Solo la de calentamiento'], 1,
    'Ir al fallo en todo cansa mucho. Mejor usarlo en algunas series, sobre todo en ejercicios simples.'],
  ['e43', 'e', '¿Cuánto descanso suele necesitar un músculo antes de volver a entrenarlo fuerte?', ['Unas 48 horas', '2 semanas', 'Nada'], 0,
    'Por eso funcionan bien las rutinas que entrenan cada músculo 2 veces por semana.'],
  ['e44', 'e', '¿Qué es mejor para la salud, el cardio HIIT o el continuo?', ['Solo HIIT', 'Solo continuo', 'Ambos sirven; lo importante es hacerlo'], 2,
    'Elige el que más disfrutes y puedas sostener en el tiempo.'],
  ['e45', 'e', '¿Qué es el NEAT?', ['Un suplemento', 'La energía que gastas moviéndote en el día fuera del ejercicio', 'Un tipo de sentadilla'], 1,
    'Caminar, subir escaleras o estar de pie suman muchas calorías a lo largo del día.'],
  ['e46', 'e', '¿Qué es un ejercicio isométrico?', ['Una contracción sin movimiento (ej. la plancha)', 'Un ejercicio con máquina', 'Correr en cerro'], 0,
    'El músculo hace fuerza, pero la articulación no se mueve.'],
  ['e47', 'e', 'En dominadas, ¿qué es el agarre prono?', ['Palmas mirando hacia adelante', 'Palmas mirando hacia ti', 'Con una sola mano'], 0,
    'Con las palmas hacia ti (supino) suelen llamarse chin-ups y trabajan más los bíceps.'],
  ['e48', 'e', '¿Qué es una serie de aproximación?', ['Una serie más liviana para acercarte de a poco al peso de trabajo', 'Una serie al fallo', 'La última serie del día'], 0,
    'No cuentan como series efectivas: sirven para preparar el cuerpo y la técnica.'],
  ['e49', 'e', 'Si llevas semanas sin subir de peso ni de reps, ¿qué puedes probar?', ['Rendirte', 'Cambiar algo: más series, otro rango de reps o descansar mejor', 'Entrenar 3 veces al día'], 1,
    'Un estancamiento suele resolverse ajustando volumen, recuperación o comida.'],
  ['e50', 'e', '¿Qué es lo más importante para ver resultados a largo plazo?', ['La constancia', 'El suplemento más caro', 'Cambiar de rutina cada semana'], 0,
    'Un plan simple que sigues por meses gana a uno perfecto que abandonas.'],

  // ---------- Nutrición ----------
  ['n1', 'n', '¿Cuánta proteína al día se recomienda para ganar músculo?', ['0,8 g por kg de peso', '1,6 a 2,2 g por kg de peso', '5 g por kg de peso'], 1,
    'Una persona de 75 kg necesitaría unos 120 a 165 g de proteína al día.'],
  ['n2', 'n', '¿Cuántas kcal tiene 1 g de grasa?', ['4', '7', '9'], 2,
    'La grasa es el macronutriente con más calorías por gramo.'],
  ['n3', 'n', '¿Cuántas kcal tiene 1 g de proteína?', ['4', '9', '0'], 0,
    'Proteína y carbohidratos tienen 4 kcal por gramo; la grasa, 9.'],
  ['n4', 'n', '¿Cuántas kcal tiene 1 g de carbohidrato?', ['9', '4', '12'], 1,
    'Igual que la proteína: 4 kcal por gramo.'],
  ['n5', 'n', '¿Cuántas kcal tiene 1 g de alcohol?', ['0', '7', '2'], 1,
    'El alcohol aporta 7 kcal por gramo y casi nada de nutrientes.'],
  ['n6', 'n', 'Aproximadamente, ¿cuántas kcal hay en 1 kg de grasa corporal?', ['1.000', '7.700', '50.000'], 1,
    'Por eso bajar 1 kg de grasa al mes es un déficit de unas 250 kcal al día.'],
  ['n7', 'n', '¿Hacer abdominales quema la grasa del abdomen?', ['Sí, justo ahí', 'No: la grasa baja en todo el cuerpo con déficit calórico', 'Solo si haces 100 al día'], 1,
    'No se puede elegir de dónde se pierde grasa. Los abdominales fortalecen, pero no "queman" la guata.'],
  ['n8', 'n', '¿Qué macronutriente es la principal fuente de energía para entrenar intenso?', ['Carbohidratos', 'Proteína', 'Fibra'], 0,
    'Los carbohidratos se guardan como glucógeno en el músculo y alimentan los esfuerzos intensos.'],
  ['n9', 'n', 'Para ganar músculo sin ganar mucha grasa, ¿cuánto comer?', ['Un poco sobre tu mantención (unas 200–400 kcal)', 'Todo lo que puedas', 'Menos que tu mantención'], 0,
    'Un superávit pequeño basta para construir músculo y limita la grasa extra.'],
  ['n10', 'n', '¿A qué ritmo es sostenible bajar de peso?', ['Unos 0,5 a 1 % de tu peso por semana', '5 kg por semana', '100 g al mes'], 0,
    'Más rápido suele costar músculo, energía y es difícil de mantener.'],
  ['n11', 'n', '¿Comer de noche engorda más?', ['Sí, todo lo que comes de noche se vuelve grasa', 'No: lo que importa es el total de calorías del día', 'Solo si comes fruta'], 1,
    'La hora importa menos que cuánto comes en total. Elige el horario que te acomode.'],
  ['n12', 'n', '¿Dónde está la proteína del huevo?', ['Solo en la clara', 'En la clara y también en la yema', 'Solo en la yema'], 1,
    'La yema tiene casi la mitad de la proteína del huevo, además de vitaminas y grasas.'],
  ['n13', 'n', '¿Cuánta fibra al día se recomienda aproximadamente?', ['5 g', '25 a 35 g', '150 g'], 1,
    'La fibra ayuda a la digestión y a sentirte satisfecho. Está en verduras, frutas, legumbres e integrales.'],
  ['n14', 'n', '¿Cómo conviene repartir la proteína en el día?', ['Toda en una comida', 'En 3 a 5 comidas, unos 20 a 40 g cada una', 'Solo después de entrenar'], 1,
    'Repartirla ayuda a mantener la construcción de músculo durante el día.'],
  ['n15', 'n', '¿Hay que tomar proteína en los 30 minutos después de entrenar?', ['Sí, o pierdes todo', 'No es tan crítico: importa más el total del día', 'Solo los lunes'], 1,
    'La famosa "ventana anabólica" es mucho más amplia de lo que se creía.'],
  ['n16', 'n', '¿Es obligatorio tomar batidos de proteína?', ['Sí, sin batido no creces', 'No: es comida en polvo, práctica pero opcional', 'Solo si eres hombre'], 1,
    'Si llegas a tu proteína con comida, no lo necesitas. Es solo una forma cómoda de sumar.'],
  ['n17', 'n', '¿Qué dosis diaria de creatina monohidrato es la más usada?', ['3 a 5 g al día', '50 g al día', '0,1 g al día'], 0,
    'No hace falta "cargar": con 3 a 5 g diarios el músculo se satura en unas semanas.'],
  ['n18', 'n', '¿Qué efecto puede tener la cafeína antes de entrenar?', ['Mejorar el rendimiento', 'Hacerte crecer el músculo sola', 'Ninguno'], 0,
    'Ayuda a rendir y a sentir menos cansancio. Ojo con tomarla tarde: afecta el sueño.'],
  ['n19', 'n', '¿Cuáles son los 3 macronutrientes?', ['Proteínas, carbohidratos y grasas', 'Vitaminas, minerales y agua', 'Calorías, azúcar y sal'], 0,
    'Son los que aportan energía (calorías). Las vitaminas y minerales son micronutrientes.'],
  ['n20', 'n', '¿Qué son los micronutrientes?', ['Las vitaminas y los minerales', 'Las proteínas', 'Los alimentos chicos'], 0,
    'Se necesitan en poca cantidad, pero son clave para la salud. Se cubren con una dieta variada.'],
  ['n21', 'n', '¿Qué macronutriente sacia más?', ['La proteína', 'El azúcar', 'El alcohol'], 0,
    'Por eso una dieta alta en proteína ayuda a pasar menos hambre al bajar de peso.'],
  ['n22', 'n', '¿Qué macronutriente gasta más energía al digerirse?', ['La grasa', 'La proteína', 'Los carbohidratos'], 1,
    'Es el "efecto térmico": parte de las calorías de la proteína se gastan en digerirla.'],
  ['n23', 'n', '¿Hay que eliminar la grasa de la dieta para bajar de peso?', ['Sí, toda', 'No: es necesaria; se ajusta, no se elimina', 'Solo la del pescado'], 1,
    'Las grasas son esenciales para las hormonas y la absorción de vitaminas.'],
  ['n24', 'n', '¿Qué es lo que realmente hace subir la grasa corporal?', ['El azúcar, aunque comas poco', 'Comer más calorías de las que gastas, vengan de donde vengan', 'Comer pan'], 1,
    'Ningún alimento engorda por sí solo: lo que suma es el exceso de calorías.'],
  ['n25', 'n', '¿Qué aportan las legumbres (porotos, lentejas, garbanzos)?', ['Solo carbohidratos', 'Proteína y fibra', 'Solo grasa'], 1,
    'Son una gran fuente de proteína vegetal, fibra y minerales, y además son baratas.'],
  ['n26', 'n', '¿Qué tipo de grasa tiene principalmente la palta?', ['Grasa saludable (monoinsaturada)', 'Grasa trans', 'No tiene grasa'], 0,
    'Es una buena grasa, pero tiene bastantes calorías: cuida la porción.'],
  ['n27', 'n', '¿Cuántas calorías tiene una bebida "zero"?', ['Casi 0', 'Lo mismo que la normal', 'El doble'], 0,
    'Usan endulzantes sin calorías. Pueden ayudar a reemplazar bebidas con azúcar.'],
  ['n28', 'n', '¿Qué sacia más?', ['Un jugo de naranja', 'Una naranja entera', 'Da lo mismo'], 1,
    'La fruta entera tiene fibra y hay que masticarla. El jugo se toma rápido y sacia menos.'],
  ['n29', 'n', '¿Qué puede ayudarte a rendir mejor en un entreno intenso?', ['Comer carbohidratos 1 a 3 horas antes', 'Entrenar después de 24 horas sin comer', 'Tomar solo agua con sal'], 0,
    'Llegar con energía (glucógeno) te ayuda a entrenar más fuerte.'],
  ['n30', 'n', '¿El ayuno intermitente quema más grasa por sí solo?', ['Sí, es mágico', 'No: funciona si te ayuda a comer menos en total', 'Hace subir de peso siempre'], 1,
    'Es una forma de organizar las comidas. Lo que manda sigue siendo el total de calorías.'],
  ['n31', 'n', '¿Qué son tus calorías de mantención?', ['Lo que comes para mantener tu peso', 'Lo mínimo para sobrevivir', 'Las calorías de los snacks'], 0,
    'Si comes menos, bajas; si comes más, subes. En Desdel lo ves en Kcal objetivo.'],
  ['n32', 'n', '¿Qué es el metabolismo basal?', ['La energía que gastas en reposo para mantenerte vivo', 'Lo que gastas entrenando', 'Lo que comes al desayuno'], 0,
    'Es la mayor parte de lo que gastas al día, incluso sin moverte.'],
  ['n33', 'n', '¿Qué es la leucina?', ['Un aminoácido clave para construir músculo', 'Un tipo de grasa', 'Una vitamina'], 0,
    'Está en carnes, huevos, lácteos y legumbres. Activa la construcción de proteína muscular.'],
  ['n34', 'n', '¿Se puede ganar músculo siendo vegetariano?', ['No, imposible', 'Sí, combinando fuentes y llegando a tu proteína', 'Solo con suplementos'], 1,
    'Legumbres, tofu, huevos, lácteos y cereales combinados cubren bien la proteína.'],
  ['n35', 'n', 'Si comes más salado de lo normal, ¿qué puede pasar en la balanza?', ['Sube un poco por retención de agua', 'Baja 2 kg de grasa', 'Nada nunca'], 0,
    'Es agua, no grasa, y se va en uno o dos días.'],
  ['n36', 'n', '¿Cuál es la mejor forma de pesarte para comparar?', ['A la misma hora, en ayunas y después del baño', 'Después de almorzar', 'Con ropa de invierno'], 0,
    'Así las condiciones son parecidas y los cambios reflejan mejor la realidad.'],
  ['n37', 'n', 'Para comparar alimentos en la etiqueta, ¿qué conviene mirar?', ['Los valores por 100 g', 'El color del envase', 'Solo la porción sugerida'], 0,
    'Las porciones cambian entre marcas; por 100 g se comparan de igual a igual.'],
  ['n38', 'n', '¿Cómo afecta el alcohol a tu progreso?', ['Ayuda a recuperarte', 'Empeora el sueño y la recuperación, y suma calorías', 'No afecta en nada'], 1,
    'Ocasionalmente y en poca cantidad afecta poco; en exceso frena tus resultados.'],
  ['n39', 'n', '¿Qué alimento tiene más proteína cada 100 g?', ['Pechuga de pollo', 'Arroz cocido', 'Plátano'], 0,
    'La pechuga tiene unos 30 g de proteína por 100 g; el arroz cocido, menos de 3.'],
  ['n40', 'n', '¿Qué tiene más calorías: 100 g de aceite o 100 g de azúcar?', ['El azúcar', 'El aceite', 'Lo mismo'], 1,
    'El aceite tiene unas 880 kcal por 100 g; el azúcar, unas 400. Una cucharada de aceite suma rápido.'],
  ['n41', 'n', '¿Cuánta agua al día es una buena guía general?', ['Unos 35 ml por kg de peso', '1 vaso', '10 litros'], 0,
    'Una persona de 70 kg tomaría unos 2,5 L. Con calor o mucho sudor, más.'],
  ['n42', 'n', 'Al empezar una dieta, ¿qué es mucho de lo que baja la primera semana?', ['Agua y glucógeno', 'Solo grasa', 'Músculo'], 0,
    'Por eso la primera semana baja rápido y después más lento. Es normal.'],
  ['n43', 'n', '¿Qué es el glucógeno?', ['Carbohidratos guardados en el músculo y el hígado', 'Una hormona', 'Un tipo de grasa'], 0,
    'Es la energía de reserva para esfuerzos intensos. Cada gramo se guarda junto con agua.'],
  ['n44', 'n', '¿Qué es la recomposición corporal?', ['Bajar grasa y subir músculo al mismo tiempo', 'Cambiar de dieta cada mes', 'Ponerse más alto'], 0,
    'Es más fácil en principiantes o al volver después de una pausa.'],
  ['n45', 'n', 'Si solo vas a cuidar un macronutriente para ganar músculo, ¿cuál?', ['La proteína', 'La grasa', 'El azúcar'], 0,
    'Llegar a tu proteína diaria es lo más importante para construir músculo.'],
  ['n46', 'n', '¿Hay que dejar la fruta para bajar de peso?', ['Sí, por el azúcar', 'No: tiene pocas calorías, fibra y vitaminas', 'Solo el plátano'], 1,
    'La fruta entera sacia y aporta mucho. No es la causa de subir de peso.'],
  ['n47', 'n', '¿Qué diferencia tiene el pan integral del blanco?', ['Tiene más fibra', 'Tiene 0 calorías', 'Ninguna'], 0,
    'Las calorías son parecidas, pero la fibra extra sacia más.'],
  ['n48', 'n', '¿Qué tiene de bueno el yogur griego o proteico?', ['Más proteína que el yogur normal', 'No tiene calorías', 'Tiene más azúcar'], 0,
    'Es una forma fácil de sumar proteína en colaciones.'],
  ['n49', 'n', '¿Dónde hay omega-3?', ['En pescados grasos como el salmón o el jurel', 'En las bebidas', 'En el pan blanco'], 0,
    'También en nueces y linaza. Ayuda a la salud del corazón.'],
  ['n50', 'n', '¿Cuál es una buena fuente de hierro?', ['Lentejas y carnes rojas', 'Agua mineral', 'Arroz blanco'], 0,
    'Acompañar las legumbres con algo de vitamina C (limón, pimentón) mejora la absorción del hierro.'],

  // ---------- Salud y recuperación ----------
  ['s1', 's', '¿Cuántas horas de sueño se recomiendan a un adulto?', ['5', '7 a 9', '11 a 12'], 1,
    'Dormir bien es cuando tu cuerpo se recupera y construye músculo.'],
  ['s2', 's', '¿Qué es la creatina?', ['Un esteroide', 'Un suplemento muy estudiado que ayuda a la fuerza', 'Un quemador de grasa'], 1,
    'Es uno de los suplementos con más evidencia y es seguro en personas sanas.'],
  ['s3', 's', '¿Qué es una señal simple de buena hidratación?', ['Orina amarilla clara', 'Orina muy oscura', 'No tener sed nunca'], 0,
    'Si está oscura, te falta agua. Si es completamente transparente, quizás estás tomando de más.'],
  ['s4', 's', '¿Qué puede pasar si duermes poco seguido?', ['Mejoras tu fuerza', 'Baja tu rendimiento y recuperación, y te da más hambre', 'Nada'], 1,
    'Dormir poco afecta la fuerza, el ánimo y las hormonas del apetito.'],
  ['s5', 's', '¿Cuánta actividad física moderada a la semana recomienda la OMS a los adultos?', ['30 minutos', '150 a 300 minutos', '20 horas'], 1,
    'Por ejemplo, 30 a 60 minutos casi todos los días. Más actividad suma más beneficios.'],
  ['s6', 's', '¿Cuántos días de fuerza a la semana recomienda la OMS como mínimo?', ['Ninguno', 'Al menos 2', 'Solo 1 al mes'], 1,
    'Entrenar fuerza protege músculos, huesos y articulaciones a cualquier edad.'],
  ['s7', 's', 'Si sientes un dolor agudo y punzante durante un ejercicio, ¿qué haces?', ['Sigues igual', 'Paras y no lo fuerzas', 'Subes el peso'], 1,
    'El dolor agudo es una señal de alerta. Si sigue, consulta a un profesional.'],
  ['s8', 's', '¿Cuándo suele aparecer el dolor muscular después de entrenar?', ['Al instante', 'Entre 24 y 72 horas después', 'Una semana después'], 1,
    'Se llama dolor muscular de aparición tardía y es normal, sobre todo con ejercicios nuevos.'],
  ['s9', 's', '¿Para qué sirve calentar?', ['Para nada', 'Para preparar el cuerpo y rendir mejor', 'Para cansarte antes'], 1,
    'Sube la temperatura del músculo y prepara la técnica para las series pesadas.'],
  ['s10', 's', '¿Cómo se estima de forma simple tu frecuencia cardíaca máxima?', ['220 menos tu edad', 'Tu peso por 2', '100 más tu edad'], 0,
    'Es solo una estimación: varía bastante entre personas.'],
  ['s11', 's', '¿Qué hace el ejercicio regular con la presión arterial?', ['Ayuda a bajarla', 'La sube siempre', 'Nada'], 0,
    'Es una de las mejores herramientas para la salud del corazón.'],
  ['s12', 's', '¿Qué hace el entrenamiento con pesas en los huesos?', ['Los debilita', 'Ayuda a fortalecerlos', 'Nada'], 1,
    'La carga estimula los huesos, algo muy importante con la edad.'],
  ['s13', 's', '¿Las mujeres que levantan pesas se ponen "enormes" fácilmente?', ['Sí, en un mes', 'No: ganan fuerza y forma, y el músculo crece lento', 'Solo si toman agua'], 1,
    'Ganar mucho músculo toma años de trabajo. Las pesas son para todos.'],
  ['s14', 's', '¿Qué efecto puede tener el estrés alto y constante?', ['Mejora la recuperación', 'Empeora el sueño y la recuperación', 'Ninguno'], 1,
    'Dormir bien, moverse y desconectarse ayuda a manejarlo.'],
  ['s15', 's', '¿Qué puede empeorar tu sueño?', ['Usar pantallas justo antes de dormir', 'Leer un libro', 'Tener la pieza oscura'], 0,
    'La luz y los estímulos de la pantalla dificultan conciliar el sueño.'],
  ['s16', 's', '¿Cuánto tiempo antes de dormir conviene dejar la cafeína?', ['10 minutos', 'Unas 6 horas o más', 'No afecta'], 1,
    'La cafeína dura varias horas en el cuerpo y puede quitarte sueño profundo.'],
  ['s17', 's', '¿Cuánto debería durar una siesta reparadora?', ['20 a 30 minutos', '3 horas', '1 minuto'], 0,
    'Una siesta corta da energía sin dejarte atontado ni afectar la noche.'],
  ['s18', 's', '¿Son necesarios los días de descanso?', ['No, son para flojos', 'Sí: ahí te recuperas y progresas', 'Solo una vez al año'], 1,
    'Sin recuperación, el cuerpo no alcanza a adaptarse al entrenamiento.'],
  ['s19', 's', '¿Cuál es una señal de que estás entrenando más de lo que te puedes recuperar?', ['Cansancio constante, peor rendimiento y mal sueño', 'Tener hambre', 'Sudar'], 0,
    'Si pasa, baja el volumen unos días, duerme más y revisa tu comida.'],
  ['s20', 's', '¿Para qué sirve trabajar la movilidad?', ['Para mantener un buen rango de movimiento', 'Para bajar de peso', 'Para nada'], 0,
    'Ayuda a hacer los ejercicios con mejor técnica y más cómodo.'],
  ['s21', 's', 'Si entrenas con mucho calor, ¿qué conviene?', ['Tomar más agua', 'No tomar agua', 'Entrenar con chaqueta'], 0,
    'Con calor se pierde más líquido. Toma a sorbos antes, durante y después.'],
  ['s22', 's', '¿Qué minerales se pierden con el sudor?', ['Sodio y potasio', 'Hierro y oro', 'Ninguno'], 0,
    'En entrenos largos o con mucho calor, conviene reponerlos con comida o bebida.'],
  ['s23', 's', '¿Qué mide el FFMI?', ['Tu masa magra para tu estatura', 'Tu fuerza máxima', 'Tus horas de sueño'], 0,
    'Es como el IMC, pero solo con lo que no es grasa. Lo ves en Desdel → Cuerpo → % Grasa.'],
  ['s24', 's', '¿Cuál es el problema principal del IMC?', ['No distingue músculo de grasa', 'Es muy difícil de calcular', 'Solo sirve en niños'], 0,
    'Una persona musculosa puede salir con "sobrepeso" aunque tenga poca grasa.'],
  ['s25', 's', '¿Qué rango de % de grasa se considera saludable en hombres adultos jóvenes?', ['2 a 4 %', 'Aprox. 8 a 20 %', '35 a 45 %'], 1,
    'En mujeres el rango saludable es más alto, aprox. 21 a 32 %, porque necesitan más grasa esencial.'],
  ['s26', 's', '¿Qué mide un plicómetro?', ['Los pliegues de grasa bajo la piel', 'La fuerza', 'La presión'], 0,
    'Con 3 pliegues, Desdel calcula tu % de grasa (fórmula de Jackson-Pollock).'],
  ['s27', 's', '¿Qué valor de cintura dividida por estatura se considera saludable?', ['Menos de 0,5', 'Más de 1', 'Exactamente 2'], 0,
    'Ejemplo: 1,75 m de estatura → cintura menor a 87 cm. Lo ves en Desdel → Cuerpo → Medidas.'],
  ['s28', 's', 'Si pasas muchas horas sentado, ¿qué ayuda?', ['Pararte y moverte cada cierto rato', 'Sentarte más derecho y nunca moverte', 'Nada'], 0,
    'Cortar el tiempo sentado con pausas activas es bueno para tu salud y tu espalda.'],
  ['s29', 's', 'Si una molestia dura más de 1 a 2 semanas o empeora, ¿qué conviene?', ['Ignorarla', 'Consultar a un profesional de salud', 'Entrenar más fuerte'], 1,
    'Un diagnóstico a tiempo evita que algo chico se vuelva una lesión larga.'],
  ['s30', 's', '¿Qué riesgos tienen los esteroides anabólicos?', ['Ninguno', 'Problemas al corazón, al hígado y hormonales', 'Solo acné'], 1,
    'Tienen efectos serios para la salud. Desdel está pensada para progresar natural.'],
  ['s31', 's', '¿Hacen falta muchos suplementos si comes bien?', ['Sí, todos', 'No: la mayoría no son necesarios', 'Solo los más caros'], 1,
    'Pocos tienen buena evidencia (como la creatina o la cafeína). La base es comida, sueño y entrenamiento.'],
  ['s32', 's', '¿De dónde obtiene el cuerpo la mayor parte de la vitamina D?', ['De la luz del sol en la piel', 'Del agua', 'Del pan'], 0,
    'También está en pescados grasos y huevos. En invierno se suele producir menos.'],
  ['s33', 's', 'En personas sanas, ¿una dieta alta en proteína daña los riñones?', ['Sí, siempre', 'No se ha visto daño en personas sanas', 'Solo los martes'], 1,
    'Si tienes una enfermedad renal, consulta con tu médico antes de cambiar tu dieta.'],
  ['s34', 's', '¿Cómo afecta fumar al rendimiento deportivo?', ['Lo mejora', 'Empeora la capacidad pulmonar y la recuperación', 'No afecta'], 1,
    'Dejar de fumar mejora rápidamente la capacidad para hacer ejercicio.'],
  ['s35', 's', '¿Qué efecto tiene el ejercicio en el ánimo?', ['Lo mejora y ayuda a bajar la ansiedad', 'Lo empeora', 'Ninguno'], 0,
    'Es una de las mejores herramientas para la salud mental.'],
  ['s36', 's', '¿Qué es la sarcopenia?', ['La pérdida de músculo con la edad', 'Un suplemento', 'Un tipo de cardio'], 0,
    'Entrenar fuerza es la mejor forma de frenarla y mantenerse independiente con los años.'],
  ['s37', 's', '¿Qué es la recuperación activa?', ['Hacer actividad suave en días de descanso, como caminar', 'Entrenar al fallo todos los días', 'Dormir 15 horas'], 0,
    'Moverse suave ayuda a sentirse mejor sin sumar fatiga.'],
  ['s38', 's', '¿Con qué suelen estar relacionados los calambres musculares al entrenar?', ['Con la fatiga del músculo', 'Con comer fruta', 'Con dormir mucho'], 0,
    'Estirar suave el músculo y descansar suele aliviarlos.'],
  ['s39', 's', '¿Cómo conviene tomar agua durante el entreno?', ['A sorbos', '2 litros de una vez', 'No tomar'], 0,
    'Tomar de a poco evita sentirse pesado y mantiene la hidratación.'],
  ['s40', 's', 'Dormir poco, ¿qué hace con tu hambre?', ['La aumenta', 'La elimina', 'Nada'], 0,
    'La falta de sueño altera las hormonas del apetito. Dormir bien ayuda a cumplir tu dieta.'],
  ['s41', 's', 'Al mejorar tu condición física, ¿qué pasa con tu pulso en reposo?', ['Suele bajar', 'Suele subir', 'No cambia'], 0,
    'Un corazón entrenado bombea más sangre en cada latido.'],
  ['s42', 's', '¿Conviene entrenar con fiebre?', ['Sí, para sudarla', 'No: mejor descansar', 'Solo piernas'], 1,
    'Entrenar con fiebre puede empeorar la enfermedad. Vuelve cuando te sientas bien.'],
  ['s43', 's', 'En el dolor lumbar común (sin una lesión seria), ¿qué suele ayudar?', ['Mantenerse activo de forma suave', 'Reposo absoluto por semanas', 'Nada'], 0,
    'Moverse con cuidado suele ayudar más que quedarse en cama. Si es fuerte o no mejora, consulta.'],
  ['s44', 's', '¿Qué ayuda a dormir mejor?', ['Acostarte y levantarte a la misma hora', 'Cambiar de horario todos los días', 'Tomar café en la noche'], 0,
    'Un horario fijo ordena tu reloj interno.'],
  ['s45', 's', '¿Cómo afecta el alcohol al sueño?', ['Empeora su calidad', 'Lo mejora', 'No afecta'], 0,
    'Aunque te dé sueño, el descanso es menos profundo y te recuperas peor.'],
  ['s46', 's', '¿Qué cantidad de pasos diarios es una buena meta de salud?', ['500', '7.000 a 10.000', '50.000'], 1,
    'Caminar más se asocia a mejor salud. Si hoy caminas poco, sube de a poco.'],
  ['s47', 's', '¿Qué le hace el ejercicio cardiovascular al corazón?', ['Lo fortalece', 'Lo debilita', 'Nada'], 0,
    'Mejora la capacidad del corazón y los pulmones.'],
  ['s48', 's', '¿Entrenar en la noche arruina el sueño?', ['Sí, siempre', 'Para la mayoría no, si no es justo antes de acostarse', 'Solo en verano'], 1,
    'Si notas que te cuesta dormir, deja un par de horas entre el entreno y la cama.'],
  ['s49', 's', '¿Qué conviene hacer después de una lesión, una vez que el profesional lo autoriza?', ['Volver de a poco, con menos peso', 'Volver con el peso de antes', 'No entrenar nunca más'], 0,
    'Una vuelta progresiva reduce el riesgo de recaer.'],
  ['s50', 's', '¿Cuál es la mejor rutina de ejercicio?', ['La que puedes mantener en el tiempo', 'La más difícil', 'La de un famoso'], 0,
    'La constancia gana. Elige algo que disfrutes y que calce con tu vida.'],

  // ---------- Difíciles (el 7º dato = 2) ----------
  ['e51', 'e', '¿Qué duración por repetición sirve para ganar músculo?', ['Exactamente 4 segundos por rep', 'Un rango amplio, aprox. 0,5 a 8 segundos por rep', 'Más de 10 segundos por rep'], 1,
    'Dentro de ese rango los resultados son parecidos. Las reps súper lentas (más de 10 s) rinden peor.', 2],
  ['e52', 'e', '¿Qué es el tiempo bajo tensión?', ['El tiempo total que el músculo trabaja durante una serie', 'El tiempo de descanso entre series', 'Lo que dura el entreno completo'], 0,
    'No es mágico por sí solo: importa más que la serie termine cerca del fallo.', 2],
  ['e53', 'e', '¿Cuánto debería durar una serie para ganar músculo?', ['Siempre 40 segundos exactos', 'No hay un tiempo mágico: importa llegar cerca del fallo', 'Mínimo 3 minutos'], 1,
    'Las series suelen durar entre 10 y 70 segundos, pero el tiempo es consecuencia de las reps y el ritmo, no la meta.', 2],
  ['e54', 'e', '¿Cómo conviene hacer la fase concéntrica (subir el peso)?', ['Con intención de moverlo rápido, sin perder la técnica', 'Siempre lo más lento posible', 'Rebotando el peso'], 0,
    'Intentar subir rápido activa más fibras y ayuda a la fuerza. La bajada, controlada.', 2],
  ['e55', 'e', '¿Cuál es el principal estímulo para que el músculo crezca?', ['La tensión mecánica', 'Sudar mucho', 'El dolor al día siguiente'], 0,
    'Que el músculo haga fuerza contra una carga alta, cerca del fallo, es la señal más importante para crecer.', 2],
  ['e56', 'e', '¿Qué es el estrés metabólico?', ['Acumulación de metabolitos (como el lactato) en series largas o con poco descanso', 'El estrés del trabajo', 'Comer poco'], 0,
    'Es la sensación de "quemazón". Se cree que aporta algo al crecimiento, pero menos que la tensión mecánica.', 2],
  ['e57', 'e', '¿Qué es la hipertrofia miofibrilar o sarcomérica?', ['Aumento de las proteínas que se contraen (miofibrillas)', 'Aumento del agua bajo la piel', 'Aumento de la grasa dentro del músculo'], 0,
    'Más miofibrillas significa más sarcómeros en paralelo: más fuerza y más tamaño.', 2],
  ['e58', 'e', '¿Qué es la hipertrofia sarcoplasmática?', ['Aumento del líquido y de los componentes no contráctiles del músculo', 'Aumento del tamaño de los huesos', 'Pérdida de músculo'], 0,
    'Se discute cuánto ocurre por separado; en la práctica ambos tipos suelen ir juntos.', 2],
  ['e59', 'e', '¿Las reps altas dan hipertrofia sarcoplasmática y las bajas sarcomérica?', ['Sí, está comprobado', 'No está demostrado: ambos tipos de entreno hacen crecer el músculo de forma parecida', 'Solo en mujeres'], 1,
    'Es una idea popular, pero la evidencia no muestra que el rango de reps elija el tipo de hipertrofia.', 2],
  ['e60', 'e', '¿Qué caracteriza a las fibras tipo I?', ['Son lentas y muy resistentes a la fatiga', 'Son las más rápidas y fuertes', 'Solo están en las piernas'], 0,
    'Funcionan sobre todo con oxígeno (aeróbicas) y predominan en esfuerzos largos.', 2],
  ['e61', 'e', '¿Qué son las fibras tipo IIa?', ['Rápidas, pero con buena resistencia (intermedias)', 'Las más lentas', 'Fibras de grasa'], 0,
    'Combinan fuerza y resistencia. Con el entrenamiento, las fibras más rápidas se vuelven más parecidas a ellas.', 2],
  ['e62', 'e', 'En humanos, ¿cómo se llama la fibra más rápida y que más se fatiga?', ['Tipo I', 'Tipo IIx (a veces llamada IIb)', 'Tipo III'], 1,
    'La IIb existe sobre todo en animales. En humanos, la más rápida es la IIx.', 2],
  ['e63', 'e', '¿Qué fibras suelen tener más potencial de crecimiento?', ['Las tipo II (rápidas)', 'Las tipo I (lentas)', 'Ninguna crece'], 0,
    'Las rápidas crecen más, pero las lentas también responden al entrenamiento.', 2],
  ['e64', 'e', '¿Qué dice el principio del tamaño (de Henneman)?', ['Las unidades motoras se activan de las más chicas a las más grandes según el esfuerzo', 'El músculo más grande siempre trabaja primero', 'Los músculos chicos no crecen'], 0,
    'Por eso, cerca del fallo, incluso con pesos livianos terminan trabajando las fibras más grandes.', 2],
  ['e65', 'e', '¿Por qué con pesos livianos también se gana músculo si llegas cerca del fallo?', ['Porque al cansarte se activan también las fibras más grandes', 'Porque el peso nunca importa', 'Con pesos livianos no se gana músculo'], 0,
    'Al acercarte al fallo, el cuerpo va sumando todas las unidades motoras disponibles.', 2],
  ['e66', 'e', '¿En qué fase del movimiento eres más fuerte?', ['En la excéntrica (bajando)', 'En la concéntrica (subiendo)', 'Igual en las dos'], 0,
    'Puedes controlar más peso al bajar que al subir. Por eso la bajada debe ser controlada.', 2],
  ['e67', 'e', '¿Qué es la hipertrofia mediada por estiramiento?', ['Más crecimiento al cargar el músculo en posiciones estiradas', 'Crecer estirando sin peso', 'Crecer mientras duermes'], 0,
    'Ejercicios con carga en la parte estirada (ej. peso muerto rumano, curl inclinado) suelen rendir muy bien.', 2],
  ['e68', 'e', '¿Qué es una serie rest-pause?', ['Llegar cerca del fallo, descansar unos segundos y seguir con más reps', 'Descansar 10 minutos entre series', 'Hacer una pausa larga en cada rep'], 0,
    'Permite sumar reps efectivas en poco tiempo.', 2],
  ['e69', 'e', '¿Qué son las cluster sets?', ['Series divididas en bloques cortos con micro-descansos', 'Series con muchos ejercicios distintos', 'Series en grupo'], 0,
    'Ayudan a mover pesos altos con mejor velocidad y técnica.', 2],
  ['e70', 'e', 'En un tempo 3-1-1-0, ¿qué significa el primer número?', ['3 segundos de bajada (excéntrica)', '3 series', '3 minutos de descanso'], 0,
    'Luego viene 1 s de pausa abajo, 1 s de subida y 0 s de pausa arriba.', 2],
  ['e71', 'e', 'En la escala RPE, ¿qué significa un RPE 8?', ['Que te quedaban unas 2 reps', 'Que hiciste 8 reps', 'Que descansaste 8 minutos'], 0,
    'RPE 10 = fallo; RPE 9 = te quedaba 1; RPE 8 = te quedaban 2. Es lo mismo que el RIR, pero al revés.', 2],
  ['e72', 'e', '¿Qué es la pre-fatiga?', ['Hacer un ejercicio de aislamiento antes de uno compuesto del mismo músculo', 'Entrenar después de dormir mal', 'Calentar 30 minutos'], 0,
    'Ej.: aperturas antes del press banca. No ha mostrado dar más crecimiento, pero sirve para variar.', 2],
  ['e73', 'e', '¿Qué es la "memoria muscular"?', ['Que recuperas más rápido el músculo que ya habías ganado', 'Que te acuerdas de la rutina', 'Un suplemento'], 0,
    'Los núcleos que ganó el músculo se mantienen bastante tiempo y facilitan volver a crecer.', 2],
  ['e74', 'e', '¿Para qué sirven las células satélite del músculo?', ['Ayudan a repararlo y le aportan nuevos núcleos', 'Transportan oxígeno', 'Queman grasa'], 0,
    'Son las células madre del músculo, clave para la reparación y el crecimiento a largo plazo.', 2],
  ['e75', 'e', '¿Qué hace la miostatina?', ['Frena el crecimiento muscular', 'Lo acelera', 'Quema grasa'], 0,
    'Es una proteína que pone un límite natural al tamaño del músculo.', 2],
  ['e76', 'e', '¿Qué vía se activa con la tensión mecánica y la leucina para construir músculo?', ['mTOR', 'La vía láctea', 'El ciclo de Krebs'], 0,
    'mTOR funciona como el interruptor que enciende la construcción de proteína muscular.', 2],
  ['e77', 'e', '¿Cuánto tiempo sigue elevada la síntesis de proteína muscular después de entrenar?', ['Unos minutos', 'Aprox. 24 a 48 horas', 'Un mes'], 1,
    'Por eso entrenar cada músculo unas 2 veces por semana aprovecha bien ese período.', 2],
  ['e78', 'e', '¿Qué sistema de energía domina en un esfuerzo máximo de unos 5 a 10 segundos?', ['El de la fosfocreatina (ATP-PC)', 'El aeróbico', 'El de las grasas'], 0,
    'Es justamente el sistema que la creatina ayuda a recargar.', 2],
  ['e79', 'e', '¿Cuánto tarda la fosfocreatina en recargarse casi por completo después de una serie intensa?', ['10 segundos', 'Unos 3 a 5 minutos', '2 horas'], 1,
    'Por eso, en series muy pesadas, los descansos largos permiten rendir más.', 2],
  ['e80', 'e', '¿Qué es el efecto de la carga repetida (repeated bout effect)?', ['Que el mismo ejercicio duele menos la segunda vez', 'Que siempre duele igual', 'Que hay que cambiar de ejercicio cada semana'], 0,
    'El músculo se adapta rápido al daño, por eso el dolor baja con las semanas.', 2],

  ['n51', 'n', 'Aproximadamente, ¿cuánto glucógeno puede guardar una persona en total?', ['Unos 40 g', 'Unos 400 a 500 g entre músculo e hígado', 'Unos 5 kg'], 1,
    'La mayoría está en los músculos; el hígado guarda unos 100 g.', 2],
  ['n52', 'n', '¿Con cuánta agua se guarda cada gramo de glucógeno?', ['Con nada de agua', 'Con unos 3 g de agua', 'Con 1 litro'], 1,
    'Por eso, al bajar los carbohidratos, el peso baja rápido al principio: es agua y glucógeno.', 2],
  ['n53', 'n', '¿Qué es la autofagia?', ['Un proceso en que las células reciclan sus partes dañadas', 'Comerse las uñas', 'Un tipo de dieta'], 0,
    'El ejercicio y el ayuno la estimulan. No hace falta ayunar días para que ocurra.', 2],
  ['n54', 'n', '¿Cuánta proteína por comida estimula bien la construcción de músculo?', ['Aprox. 0,4 g por kg de peso', '5 g', '200 g'], 0,
    'Para alguien de 75 kg son unos 30 g por comida.', 2],
  ['n55', 'n', '¿Cuánta leucina por comida se considera suficiente para activar la síntesis de proteína?', ['Unos 2 a 3 g', '0,1 g', '30 g'], 0,
    'Unos 25 a 30 g de proteína animal ya la aportan. Con proteína vegetal se necesita un poco más.', 2],
  ['n56', 'n', '¿Cuál es la diferencia entre la proteína whey y la caseína?', ['La whey se digiere rápido y la caseína lento', 'Son exactamente lo mismo', 'La caseína no tiene proteína'], 0,
    'Ambas vienen de la leche. La caseína se usa a veces antes de dormir.', 2],
  ['n57', 'n', '¿Sirve tomar proteína antes de dormir?', ['Puede ayudar a construir músculo durante la noche', 'Hace subir de peso siempre', 'Impide dormir'], 0,
    'Lo más importante sigue siendo el total diario, pero es una buena opción.', 2],
  ['n58', 'n', '¿Qué parte de las calorías de la proteína se gasta en digerirla?', ['Aprox. 20 a 30 %', '1 %', '90 %'], 0,
    'En los carbohidratos es aprox. 5 a 10 %, y en las grasas aprox. 0 a 3 %.', 2],
  ['n59', 'n', '¿Qué parte de tu gasto diario es el metabolismo basal?', ['Aprox. 60 a 70 %', '5 %', '100 %'], 0,
    'El resto es la digestión, el ejercicio y la actividad diaria (NEAT).', 2],
  ['n60', 'n', '¿Qué es la termogénesis adaptativa?', ['Una baja del gasto de energía en dietas largas, mayor a la esperada por el peso perdido', 'Sudar más en verano', 'Un suplemento'], 0,
    'Por eso las pausas de dieta (diet breaks) o subir calorías un tiempo pueden ayudar.', 2],
  ['n61', 'n', '¿Qué es el índice glicémico?', ['Qué tan rápido un alimento sube la glucosa en sangre', 'Las calorías de un alimento', 'La cantidad de proteína'], 0,
    'Si la comida tiene fibra, proteína o grasa, la glucosa sube más lento.', 2],
  ['n62', 'n', '¿Qué es la cetosis?', ['Cuando el cuerpo usa cetonas como energía por falta de carbohidratos', 'Una enfermedad del estómago', 'Un tipo de cardio'], 0,
    'Ocurre con dietas muy bajas en carbohidratos o con ayunos largos.', 2],
  ['n63', 'n', '¿Para qué sirve la beta-alanina?', ['Ayuda en esfuerzos intensos de 1 a 4 minutos', 'Hace crecer el músculo por sí sola', 'Reemplaza la proteína'], 0,
    'Sube la carnosina del músculo, que amortigua la acidez. El hormigueo que da es normal.', 2],
  ['n64', 'n', '¿Por qué el jugo de betarraga puede mejorar el rendimiento?', ['Por sus nitratos, que mejoran el uso del oxígeno', 'Por el azúcar', 'No sirve'], 0,
    'Se ha visto sobre todo en esfuerzos de resistencia.', 2],
  ['n65', 'n', '¿El cardio en ayunas quema más grasa al final del día?', ['Sí, el doble', 'No: la pérdida de grasa total es parecida a hacerlo comido', 'Hace ganar grasa'], 1,
    'Quema más grasa durante la sesión, pero el cuerpo lo compensa el resto del día.', 2],

  ['s51', 's', '¿Qué es el VO2 máx?', ['La máxima cantidad de oxígeno que tu cuerpo puede usar', 'El máximo peso que levantas', 'Tu pulso en reposo'], 0,
    'Es uno de los mejores indicadores de condición física y de salud a largo plazo.', 2],
  ['s52', 's', '¿Qué es el cardio en zona 2?', ['Cardio suave a moderado en el que todavía puedes hablar', 'Un sprint máximo', 'Cardio en el segundo piso del gym'], 0,
    'Mejora tu base aeróbica sin cansarte tanto como para afectar tus entrenos de fuerza.', 2],
  ['s53', 's', '¿Qué es el EPOC?', ['El oxígeno extra que consumes después de entrenar', 'Un suplemento', 'Una lesión'], 0,
    'Es real, pero quema menos calorías extra de lo que se suele decir.', 2],
  ['s54', 's', '¿El ácido láctico causa el dolor muscular del día siguiente?', ['Sí, siempre', 'No: el lactato se elimina en pocas horas', 'Solo en las piernas'], 1,
    'El dolor tardío viene del daño y la inflamación de las fibras, no del lactato.', 2],
  ['s55', 's', '¿Qué hace el cuerpo con el lactato?', ['Lo usa como combustible', 'Lo guarda para siempre', 'Lo convierte en grasa'], 0,
    'El lactato es energía útil: el corazón y los músculos lo reutilizan.', 2],
  ['s56', 's', '¿Qué puede indicar una variabilidad de la frecuencia cardíaca (VFC o HRV) más baja de lo normal para ti?', ['Que podrías estar menos recuperado', 'Que estás más fuerte', 'Nada'], 0,
    'Muchos relojes la miden. Sirve comparándola contigo mismo, no con otras personas.', 2],
  ['s57', 's', '¿Cuál es la diferencia entre "overreaching" y sobreentrenamiento?', ['El overreaching se recupera en días o semanas; el sobreentrenamiento puede tomar meses', 'Son lo mismo', 'El sobreentrenamiento se cura en 1 día'], 0,
    'Una sobrecarga planificada corta, seguida de descanso, puede hacerte progresar.', 2],
  ['s58', 's', '¿Qué se adapta más lento al entrenamiento?', ['Los tendones', 'Los músculos', 'Los dos igual'], 0,
    'Por eso conviene subir las cargas de a poco, aunque el músculo se sienta capaz.', 2],
  ['s59', 's', '¿Desde cuánta deshidratación puede empezar a bajar tu rendimiento?', ['Desde perder aprox. 2 % de tu peso en sudor', 'Desde perder 20 %', 'Nunca baja'], 0,
    'En una persona de 75 kg, perder 1,5 kg de sudor ya se nota.', 2],
  ['s60', 's', '¿Qué es la grasa visceral?', ['La que rodea los órganos dentro del abdomen', 'La grasa bajo la piel de los brazos', 'La grasa de los alimentos'], 0,
    'Es la más relacionada con el riesgo cardiovascular. Una cintura grande es una señal.', 2],
  ['s61', 's', '¿Qué hace el ejercicio con la sensibilidad a la insulina?', ['La mejora', 'La empeora', 'Nada'], 0,
    'Los músculos entrenados captan mejor la glucosa. Es clave para prevenir la diabetes tipo 2.', 2],
  ['s62', 's', '¿La subida de testosterona justo después de entrenar predice cuánto músculo ganas?', ['Sí, totalmente', 'No: esos picos cortos no explican el crecimiento', 'Solo en mujeres'], 1,
    'Lo que más importa es el entrenamiento, la proteína y el descanso.', 2],
  ['s63', 's', '¿Por qué baja el metabolismo con la edad?', ['En buena parte por la pérdida de músculo y de actividad', 'Por el color del pelo', 'No baja nunca'], 0,
    'Mantener el músculo con entrenamiento de fuerza ayuda a frenar esa baja.', 2],
  ['s64', 's', '¿Qué pesa más, 1 kg de músculo o 1 kg de grasa?', ['El músculo', 'La grasa', 'Lo mismo, pero el músculo ocupa menos espacio'], 2,
    'Por eso puedes verte más delgado con el mismo peso si ganas músculo y pierdes grasa.', 2],
  ['s65', 's', 'Si tienes presión alta y levantas pesado, ¿qué conviene?', ['Consultar a tu médico y no aguantar la respiración mucho rato', 'Aguantar la respiración lo más posible', 'No importa'], 0,
    'Aguantar el aire mucho rato sube bastante la presión durante el esfuerzo.', 2],
];
